name: Last MOe AI Agent

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  run-cli:
    name: Run CLI Agent
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo from ai-coding-agent branch
        run: |
          git clone --branch ai-coding-agent https://github.com/mhamidawad/New-AI-Agent.git
          mv New-AI-Agent/ai_coding_agent ./ai-coding-agent
          ls -la ai-coding-agent

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'





      - name: Run AI Agent CLI
        run: |
                python --version
                python -m ai_coding_agent.chat
